# Generated by Django 4.1.3 on 2022-11-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import kingbuy.account.models
import kingbuy.core.utils.json_serializer
import oauthlib.common
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('private_meta', models.JSONField(blank=True, default=dict, encoder=kingbuy.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=kingbuy.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('first_name_kannji', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name_kannji', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.CharField(blank=True, max_length=6, null=True)),
                ('gender', models.CharField(blank=True, max_length=256, null=True)),
                ('birth', models.DateField(default=django.utils.timezone.now, null=True)),
                ('work', models.CharField(blank=True, max_length=256, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user-avatars')),
            ],
            options={
                'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'スタッフ管理'), ('impersonate_users', 'Impersonate customers.')),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('street_address_1', models.CharField(blank=True, max_length=256)),
                ('street_address_2', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('city_area', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', django_countries.fields.CountryField(default='JP', max_length=2)),
                ('country_area', models.CharField(blank=True, max_length=128)),
                ('phone', kingbuy.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PLACED_ORDER', 'placed_order'), ('NOTE_ADDED_TO_ORDER', 'note_added_to_order'), ('DIGITAL_LINK_DOWNLOADED', 'digital_link_downloaded'), ('CUSTOMER_DELETED', 'customer_deleted'), ('NAME_ASSIGNED', 'name_assigned'), ('EMAIL_ASSIGNED', 'email_assigned'), ('NOTE_ADDED', 'note_added')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=kingbuy.core.utils.json_serializer.CustomJsonEncoder)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_meta', models.JSONField(blank=True, default=dict, encoder=kingbuy.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=kingbuy.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this service.', related_name='service_set', related_query_name='service', to='auth.permission', verbose_name='service account permissions')),
            ],
            options={
                'permissions': (('manage_service_accounts', 'Manage service account'),),
            },
        ),
        migrations.CreateModel(
            name='ServiceAccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('auth_token', models.CharField(default=oauthlib.common.generate_token, max_length=30, unique=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='account.serviceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
