# Generated by Django 4.1.3 on 2022-11-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_stock', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerevent',
            name='barter_manage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_stock.bartermanage'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='manual_inventory_manage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_stock.manualinventorymanage'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='order_manage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_stock.ordermanage'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='store_to_store_manage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_stock.storetostoremanage'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='account.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='addresses_2',
            field=models.ManyToManyField(blank=True, related_name='user_addresses_2', to='account.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
